#!/usr/bin/env python3
"""Assemble src/core/asm/rayo.asm and regenerate src/core/rayo_loader.inc.

    tools/rayo/build_loader.py [path/to/sjasmplus]

The generated include is committed, so building k7zx never needs an
assembler; run this only after changing rayo.asm.  sjasmplus 1.20 or later
(https://github.com/z00m128/sjasmplus).
"""
import os, re, shutil, subprocess, sys, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
SRC = os.path.join(REPO, 'src', 'core', 'asm', 'rayo.asm')
OUT = os.path.join(REPO, 'src', 'core', 'rayo_loader.inc')

# symbols the converter patches or needs to know about
WANT = ['area0', 'area0end', 'area1', 'area1end', 'area2', 'area2end', 'area3', 'area3end',
        'area4', 'area4end', 'dzxstart', 'dzx', 'edge', 'main', 'dec', 'sync', 'sync_go',
        'sync_inv', 'term', 'finish', 'error', 'segtab', 'presetn', 'presetf', 'presets',
        'decomp', 'dsrc', 'ddst', 'eiop', 'jpop', 'boot', 'bootdata']

def main():
    asm = sys.argv[1] if len(sys.argv) > 1 else (shutil.which('sjasmplus') or 'sjasmplus')
    with tempfile.TemporaryDirectory() as tmp:
        shutil.copy(SRC, tmp)
        r = subprocess.run([asm, '--nologo', '--sym=rayo.sym', 'rayo.asm'], cwd=tmp,
                           capture_output=True, text=True)
        if r.returncode != 0 or 'Errors: 0' not in r.stdout + r.stderr:
            sys.exit(r.stdout + r.stderr)
        top = open(os.path.join(tmp, 'rayo_top.bin'), 'rb').read()
        boot = open(os.path.join(tmp, 'rayo_boot.bin'), 'rb').read()
        sym = {}
        for line in open(os.path.join(tmp, 'rayo.sym')):
            m = re.match(r'([\w.]+): EQU 0x([0-9A-Fa-f]+)', line)
            if m: sym[m.group(1)] = int(m.group(2), 16)
    def arr(name, data):
        rows = [', '.join('0x%02x' % b for b in data[i:i + 16]) for i in range(0, len(data), 16)]
        return 'inline constexpr std::uint8_t %s[%d] = {\n    %s};\n' % (name, len(data), ',\n    '.join(rows))
    out = ['// Generated by tools/rayo/build_loader.py from src/core/asm/rayo.asm -- do not edit.',
           '// The Rayo loader: an image of its two pages ($%04X..$%04X) and the boot code' % (sym['area0'] & 0xff00, (sym['area0'] & 0xff00) + len(top) - 1),
           '// that runs inside the BASIC line, plus the addresses the converter patches.',
           '#pragma once', '#include <cstdint>', 'namespace k7zx::rayo {',
           'inline constexpr std::uint16_t kPage = 0x%04x;' % (sym['area0'] & 0xff00)]
    for w in WANT:
        out.append('inline constexpr std::uint16_t k_%s = 0x%04x;' % (w.replace('.', '_'), sym[w]))
    out.append(arr('kTop', top))
    out.append(arr('kBoot', boot))
    out.append('}  // namespace k7zx::rayo')
    open(OUT, 'w').write('\n'.join(out) + '\n')
    print(f'{OUT}: top {len(top)} bytes, boot {len(boot)} bytes')

if __name__ == '__main__':
    main()
