#!/usr/bin/env python3
"""Generate synthetic ZX Spectrum tape / snapshot files for the k7zx tests.

Everything here is written from the published TAP / TZX / SNA / Z80 format
descriptions; no sample data from the original project is used.
"""

import os
import struct
import sys


def basic_line(number, tokens: bytes) -> bytes:
    """One tokenised BASIC line: line number, length, body, CR."""
    body = tokens + b"\r"
    return struct.pack("<HH", number, len(body)) + body


def make_basic_program() -> bytes:
    # 10 REM generated by k7zx-tests
    rem = b"\xea" + b"generated by k7zx-tests" + b"\r"
    prog = struct.pack("<HH", 10, len(rem)) + rem
    # 20 CLEAR 30000: LOAD "" CODE
    load = b'\xfd' + b"\xb0" + b"30000" + b"\xb0" + b":" + b"\xef" + b'\xb0\xb0' + b"\xaf"
    prog += basic_line(20, load)
    # 30 RANDOMIZE USR 32768
    usr = b"\xf9" + b"\xc0" + b"\xb0" + b"32768" + b"\xb0"
    prog += basic_line(30, usr)
    return prog


def make_code_block() -> bytes:
    """~2 KiB of Z80 code (a plausible 'game' payload)."""
    out = bytearray()
    for i in range(2048):
        out.append((i * 37 + (i >> 3) * 11) & 0xFF)
    return bytes(out)


def tap_block(flag: int, payload: bytes) -> bytes:
    body = bytes([flag]) + payload
    return struct.pack("<H", len(body)) + body


def make_tap() -> bytes:
    prog = make_basic_program()
    code = make_code_block()
    out = bytearray()
    out += tap_block(0x00, bytes([0x00]) + b"tester".ljust(10, b"\x00") +
                     struct.pack("<HHH", len(prog), 30, 0) + bytes([0]))
    out += tap_block(0xFF, prog)
    out += tap_block(0x00, bytes([0x03]) + b"payload".ljust(10, b"\x00") +
                     struct.pack("<HHH", len(code), 32768, 0) + bytes([0]))
    out += tap_block(0xFF, code)
    return bytes(out)


def make_golden_tap() -> bytes:
    """A well-formed three-block tape, as a real one would be:

        10 CLEAR 32767: LOAD "" SCREEN$: LOAD "" CODE: RANDOMIZE USR 32768

    then a SCREEN$ and a CODE block at 32768 that starts with DI; HALT, so a
    Spectrum (or tools/zxload) stops once the program runs.  Numbers carry
    their hidden 5-byte forms, names are space padded, blocks have real
    checksums.  The payload bytes come from a fixed LCG so they never change:
    tests/golden_k7zx43.inc holds hashes of the WAVs k7zx 4.3 itself makes
    from this tape.  Do not change it without regenerating that file.
    """
    state = [0x1234]

    def rnd() -> int:
        state[0] = (state[0] * 1103515245 + 12345) & 0x7FFFFFFF
        return (state[0] >> 16) & 0xFF

    def num(n: int) -> bytes:
        return str(n).encode() + b"\x0e\x00\x00" + struct.pack("<H", n) + b"\x00"

    def block(flag: int, payload: bytes) -> bytes:
        data = bytes([flag]) + payload
        x = 0
        for c in data:
            x ^= c
        return tap_block(flag, payload + bytes([x]))

    body = (b"\xfd" + num(32767) + b":\xef\"\"\xaa" + b":\xef\"\"\xaf" +
            b":\xf9\xc0" + num(32768) + b"\x0d")
    prog = struct.pack(">H", 10) + struct.pack("<H", len(body)) + body
    screen = bytes(rnd() for _ in range(6912))
    code = b"\xf3\x76" + bytes(rnd() for _ in range(3070))
    out = bytearray()
    out += block(0x00, bytes([0]) + b"golden    " + struct.pack("<HHH", len(prog), 10, len(prog)))
    out += block(0xFF, prog)
    out += block(0x00, bytes([3]) + b"screen    " + struct.pack("<HHH", 6912, 16384, 32768))
    out += block(0xFF, screen)
    out += block(0x00, bytes([3]) + b"code      " + struct.pack("<HHH", len(code), 32768, 32768))
    out += block(0xFF, code)
    return bytes(out)


def make_tzx(tap: bytes) -> bytes:
    """A TZX container around the TAP payload.

    KNOWN LIMITATION: k7zx only unpacks 0x10 Standard Speed Data blocks, and
    the walker's header-only branch does not register a block, so this sample
    yields zero usable blocks.  It is still worth having -- the walker has to
    skip these three block types without tripping over them, and the high speed
    and normal-mode converter both run on the result -- but it does not exercise
    block extraction.  See the TZX section of the README.
    """
    # TZX header: "ZXTape!" + 0x1A + major + minor  (10 bytes, no start ID)
    out = bytearray(b"ZXTape!\x1a\x01\x14")
    # 0x14 pure data block describing the whole TAP payload
    payload = tap
    out += bytes([0x14]) + struct.pack("<HH", 855, 1710) + bytes([8])
    out += struct.pack("<H", 1000)
    out += struct.pack("<I", len(payload))[:3]
    out += payload
    # a pure tone and a pulse sequence so the block walker has to skip them
    out += bytes([0x12]) + struct.pack("<HH", 1000, 100)
    out += bytes([0x13]) + bytes([4]) + struct.pack("<HHHH", 800, 800, 800, 800)
    return bytes(out)


def make_sna48k() -> bytes:
    """48K .SNA: 27 byte header + 48 KiB of memory (pages 5, 2, 5).

    Header layout:
      0 I | 1 HL' | 3 DE' | 5 BC' | 7 AF' | 9 HL | 11 DE | 13 BC
      15 AF | 17 SP | 19 IY | 21 IX | 23 IFF2 | 24 R | 25 flags | 26 border
    """
    header = bytearray(27)
    header[0] = 0x3F                       # I
    struct.pack_into("<H", header, 1, 0xFF56)   # HL'
    struct.pack_into("<H", header, 3, 0xFF57)   # DE'
    struct.pack_into("<H", header, 5, 0xFF58)   # BC'
    struct.pack_into("<H", header, 7, 0xFF59)   # AF'
    struct.pack_into("<H", header, 9, 0x1234)   # HL
    struct.pack_into("<H", header, 11, 0x5678)  # DE
    struct.pack_into("<H", header, 13, 0x00FF)  # BC
    struct.pack_into("<H", header, 15, 0x00FE)  # AF
    struct.pack_into("<H", header, 17, 0xFF57)  # SP
    struct.pack_into("<H", header, 19, 0xFF5A)  # IY
    struct.pack_into("<H", header, 21, 0xFF5B)  # IX
    header[23] = 0x04                      # IFF2, interrupts enabled
    header[24] = 0x11                      # R
    header[25] = 0x01                      # IM 1
    header[26] = 7                         # border
    mem = bytearray()
    mem += bytes((i * 7) & 0xFF for i in range(0x4000))       # page 5
    mem += bytes((i * 13 + 5) & 0xFF for i in range(0x4000))  # page 2
    mem += bytes((i * 29 + 11) & 0xFF for i in range(0x4000)) # page 5 again
    return bytes(header) + bytes(mem)


def make_z80_v1() -> bytes:
    """Version 1 .Z80: 30 byte header + 48 KiB of raw memory.

    Header layout:
      0-1 AF | 2-3 BC | 4-5 HL | 6-7 PC | 8-9 SP | 10 I | 11 R | 12 flags
      13-14 DE | 15-16 BC' | 17-18 DE' | 19-20 HL' | 21-22 AF'
      23-24 IY | 25-26 IX | 27 IFF1 | 28 IFF2 | 29 IM/128K flags
    """
    header = bytearray(30)
    struct.pack_into("<H", header, 0, 0x00FE)    # AF
    struct.pack_into("<H", header, 2, 0x00FF)    # BC
    struct.pack_into("<H", header, 4, 0x1234)    # HL
    struct.pack_into("<H", header, 6, 0x1234)    # PC
    struct.pack_into("<H", header, 8, 0xFFFF)    # SP
    header[10] = 0x3F                            # I
    header[11] = 0x11                            # R
    header[12] = 0x0E                            # border 7, uncompressed
    struct.pack_into("<H", header, 13, 0xFF57)   # DE
    struct.pack_into("<H", header, 15, 0xFF58)   # BC'
    struct.pack_into("<H", header, 17, 0xFF59)   # DE'
    struct.pack_into("<H", header, 19, 0xFF5A)   # HL'
    struct.pack_into("<H", header, 21, 0xFF5B)   # AF'
    struct.pack_into("<H", header, 23, 0xFF5A)   # IY
    struct.pack_into("<H", header, 25, 0xFF5B)   # IX
    header[27] = 0x01                            # IFF1, interrupts enabled
    header[28] = 0x01                            # IFF2
    header[29] = 0x01                            # IM 1, 48K
    mem = bytearray()
    mem += bytes((i * 7) & 0xFF for i in range(0x4000))
    mem += bytes((i * 13 + 5) & 0xFF for i in range(0x4000))
    mem += bytes((i * 29 + 11) & 0xFF for i in range(0x4000))
    return bytes(header) + bytes(mem)



# --- 128K snapshots ---------------------------------------------------------
# The 128K path (convertSnapshot128K / relocate128Code, driving the 76-byte
# multi_128 blob) had no fixture at all, so it had never executed. A 128K .SNA
# is exactly 131103 bytes when the RAM currently under the ROM is page 7: the
# reader then has to copy all five remaining banks out of the file.

def make_sna128k() -> bytes:
    """128K .SNA: 27 byte header, pages 5 and 2, the RAM under ROM, then PC,
    the 7FFD port value and the five remaining banks.

    page = 0x0F sets bit 3, which is the branch that relocates the 76-byte
    multi_128 blob instead of leaving it in place, and makes page & 7 == 7 so
    every other bank has to be read from the file -- giving exactly 131103
    bytes, one of the two sizes the reader accepts.
    """
    header = bytearray(27)
    header[0] = 0x3F
    struct.pack_into("<H", header, 1, 0xFF56)
    struct.pack_into("<H", header, 9, 0x1234)
    struct.pack_into("<H", header, 13, 0x00FF)
    struct.pack_into("<H", header, 15, 0x00FE)
    struct.pack_into("<H", header, 17, 0xFF57)
    struct.pack_into("<H", header, 19, 0xFF5A)
    struct.pack_into("<H", header, 21, 0xFF5B)
    header[23] = 0x04
    header[24] = 0x11
    header[25] = 0x01
    header[26] = 7

    def page(seed: int) -> bytes:
        return bytes((i * seed + seed) & 0xFF for i in range(0x4000))

    out = bytearray(header)
    out += page(7)                 # -> pages[5]
    out += page(13)                # -> pages[2]
    out += page(0x0F + 3)          # -> pages[7 & 0x0F] == pages[7]
    out += struct.pack("<H", 0x8000)   # PC
    out += bytes([0x0F])                # 7FFD port value
    # The original's dir_pages pointer is bufferfile + 49183, one byte past the
    # end of the page byte, so that byte goes unread. 49179 + 2 + 1 + 1 + 5*0x4000
    # is exactly the 131103 the reader tests for.
    out += bytes([0x00])                # the skipped byte
    # dir_pages starts at 27 + 49152 + 2 == 49183 and the reader consumes five
    # banks from there.
    for seed in (17, 19, 23, 29, 31):
        out += page(seed)
    assert len(out) == 131103, len(out)
    return bytes(out)


def _z80_compress(data: bytes) -> bytes:
    """Minimal .Z80 page compression: 0xED 0xED <run> <value> for runs of four
    or more, literals otherwise. Longest-match is not needed for a fixture."""
    out = bytearray()
    i = 0
    while i < len(data):
        run = 1
        while run < 255 and i + run < len(data) and data[i + run] == data[i]:
            run += 1
        if run >= 4:
            out += bytes([0xED, 0xED, run, data[i]])
            i += run
        else:
            out.append(data[i])
            i += 1
    return bytes(out)


def make_z80_128k() -> bytes:
    """Version 2 .Z80 in 128K hardware mode: a 30 byte header, the extra
    header's length (2 bytes) and the 23 byte extra header, then one
    [length][page][data] block per bank."""
    header = bytearray(30)
    struct.pack_into("<H", header, 0, 0x00FE)    # AF
    struct.pack_into("<H", header, 2, 0x00FF)    # BC
    struct.pack_into("<H", header, 4, 0x1234)    # HL
    struct.pack_into("<H", header, 6, 0)        # PC == 0 selects v2/v3
    struct.pack_into("<H", header, 8, 0xFFFF)   # SP
    header[10] = 0x3F
    header[11] = 0x11
    header[12] = 0x0E                            # border 7, uncompressed
    struct.pack_into("<H", header, 13, 0xFF57)
    struct.pack_into("<H", header, 15, 0xFF58)
    struct.pack_into("<H", header, 17, 0xFF59)
    struct.pack_into("<H", header, 19, 0xFF5A)
    struct.pack_into("<H", header, 21, 0xFF5B)
    struct.pack_into("<H", header, 23, 0xFF5A)
    struct.pack_into("<H", header, 25, 0xFF5B)
    header[27] = 0x01
    header[28] = 0x01
    header[29] = 0x02                            # bit 1: 128K machine
    # Version 2: a 16-bit extra-header length at 30, then the 23 byte extra
    # header: [0..1] PC, [2] hardware (3 = 128K in version 2), [3] port 7FFD.
    extra = bytearray(23)
    struct.pack_into("<H", extra, 0, 0x8000)     # PC
    extra[2] = 3                                 # 128K
    extra[3] = 0x0F                              # port 7FFD

    out = bytearray(header) + struct.pack("<H", len(extra)) + bytes(extra)

    def block(page_num: int, seed: int) -> bytes:
        raw = bytes((i * seed + seed * 3) & 0xFF for i in range(0x4000))
        comp = _z80_compress(raw)
        # A 260 byte page is the original's "unused bank" marker: it is the
        # length of a maximally run-compressed 16 KiB page of one repeated byte.
        assert len(comp) != 260, (seed, len(comp))
        return struct.pack("<HB", len(comp), page_num) + comp

    # 8 -> pages[5], 5 -> pages[2], then 3..10 -> banks 0..7.
    for page_num, seed in ((8, 7), (5, 13), (3, 17), (4, 19), (6, 23),
                           (7, 29), (9, 31), (10, 37)):
        out += block(page_num, seed)
    return bytes(out)


# --- .SBB and .hex ----------------------------------------------------------
# Both readers were only ever fed random bytes by the fuzzer, which proves they
# do not crash but never exercises a successful parse.

def make_sbb() -> bytes:
    """SCL86 tape-block container, laid out as original/zxfiles.h declares it
    under #pragma pack(1):

      header  sbb_version[3] machine[5] extra_info[8] nombre[16]
              caux origin n_blocks poke_ffff clear_sp usr_pc        = 40 bytes
      block   blockname[16] size param3 block_type h_chksum
              ini jump exec d_chksum data[0x10000]                 = 28 bytes

    This fixture used to be written with a 48 byte header and with clear_sp,
    usr_pc and ini one or more bytes off, i.e. it was generated from the same
    misreading of the struct that the reader had, so the two agreed and the
    wrongness was invisible."""
    out = bytearray(40)
    out[0:3] = b"SB\x00"       # sbb_version
    out[3:8] = b"ZXZXZ"          # machine
    out[8:16] = b"k7zx".ljust(8, b"\x00")   # extra_info
    out[16:32] = b"fixture".ljust(16, b"\x00")  # nombre
    out[32:36] = bytes([0, 0, 2, 0])  # caux, origin, n_blocks, poke_ffff
    struct.pack_into("<H", out, 36, 0xBDB8)   # clear_sp
    struct.pack_into("<H", out, 38, 0x4900)   # usr_pc

    def block(payload: bytes, start: int, block_type: bytes) -> bytes:
        head = bytearray(28)
        head[0:16] = b"block".ljust(16, b"\x00")
        struct.pack_into("<H", head, 16, len(payload))
        struct.pack_into("<H", head, 18, 0)     # param3
        head[20] = block_type[0]                # block_type
        struct.pack_into("<H", head, 22, start)  # ini
        struct.pack_into("<H", head, 25, 0)     # exec
        return bytes(head) + payload

    code = bytes((i * 7) & 0xFF for i in range(0xC000))
    out += block(code[:0x4000], 0x4000, b"\x00")
    out += block(code[0x4000:0x8000], 0x8000, b"\x00")
    return bytes(out)


def make_hex() -> bytes:
    """A raw hex dump: 0x1800 bytes of ASCII, loaded at 0x4000. This is *not* an
    Intel HEX record file -- the original read it without record headers."""
    out = bytearray()
    for i in range(0x1800):
        out.append((i * 7 + 3) & 0xFF)
    return "".join("%02X" % b for b in out).encode("ascii")


def main() -> int:
    out_dir = sys.argv[1] if len(sys.argv) > 1 else "tests/data"
    os.makedirs(out_dir, exist_ok=True)
    tap = make_tap()
    files = {
        "test.tap": tap,
        "golden.tap": make_golden_tap(),
        "test.tzx": make_tzx(tap),
        "test48k.sna": make_sna48k(),
        "test48k.z80": make_z80_v1(),
        "test128k.sna": make_sna128k(),
        "test128k.z80": make_z80_128k(),
        "test.sbb": make_sbb(),
        "test.hex": make_hex(),
    }
    for name, blob in files.items():
        path = os.path.join(out_dir, name)
        with open(path, "wb") as f:
            f.write(blob)
        print(f"{path}: {len(blob)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
