#!/usr/bin/env python3
"""make_golden.py K7ZX43 TAPE OUT.inc

Run the k7zx 4.3 engine (built by build.sh) over every technique, speed,
sample rate and loading scheme k7zx 4.3 offered, hash each WAV, and write the
table tests/test_zxcode.cpp checks the port against.

The speeds are the ones 4.3's settings form made selectable for each
technique (SettingdForm.cpp, MetodoCmbBxChange).  Two combinations are left
out on purpose because the port deliberately differs -- see DIVERGENCES.
"""
import os
import subprocess
import sys
import tempfile

S = {"8.00": 32, "7.00": 28, "6.00": 24, "5.00": 20, "4.00": 16, "3.50": 14, "3.00": 12,
     "2.75": 11, "2.50": 10, "2.25": 9, "2.00": 8, "1.75": 7, "1.50": 6, "1.33": 4, "1.25": 5}
# method number: (name, selectable speeds)
HISPEED = {
    0: ("rom", ["3.00", "2.50"]),
    1: ("milks", ["3.50", "2.75", "2.50", "2.25", "1.75"]),
    2: ("fsk", ["8.00", "7.00", "6.00", "5.00", "4.00", "3.00", "2.50"]),
    3: ("slow", ["4.00", "3.50", "3.00", "2.50"]),
    4: ("delta", ["3.50", "3.00", "2.75", "2.25", "1.75"]),
    5: ("raudo", ["2.75", "2.50", "2.25", "1.75"]),
    6: ("ultra", ["3.00", "2.50", "2.00", "1.50"]),
    7: ("npu", ["2.50", "2.00", "1.75", "1.25"]),
    8: ("fi", ["8.00", "7.00", "6.00", "5.00", "4.00", "3.00"]),
    9: ("fiq", ["3.50", "3.00", "2.75", "2.50", "2.25", "2.00", "1.75"]),
    10: ("manchester", ["4.00", "3.00", "2.00"]),
    11: ("manchester-dif", ["4.00", "3.00", "2.00"]),
    12: ("escurrido", ["2.50", "2.25", "2.00", "1.50", "1.33"]),
}
# The low-rate "Ma non troppo" techniques (Method 13-18) were removed in step 15
# and Veloz (19) never existed here, so no MUSIC cases are generated: every row
# below has the low-rate flag clear.  The table is regenerated wholesale, so the
# rows the previous run wrote for that mode are simply not reproduced.

DIVERGENCES = {
    # Fi 3.00: the port's loader differs here and 4.3's WAV does not load
    # (verified with tools/zxload); the mechanism is not established.  See the
    # "Fi 3.00" note in README.md and the comment on case kFi in zxcode.cpp.
    (8, 12, 44100), (8, 12, 48000),
    # Raudo 1.75 at 48 kHz: the 262-byte line runs past the end of
    # raudo48000; 4.3's 360-byte memcpy filled that dead padding with
    # whatever array followed it in memory, the port writes zeros.
    (5, 7, 48000),
}


def fnv1a64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    exe, tape, out = sys.argv[1:4]
    rows = []
    with tempfile.TemporaryDirectory() as tmp:
        wav = os.path.join(tmp, "o.wav")
        cases = []
        for m, (_, speeds) in HISPEED.items():
            for sp in speeds:
                for rate in (44100, 48000):
                    if (m, S[sp], rate) in DIVERGENCES:
                        continue
                    for scheme in (1, 2, 3):
                        cases.append((0, m, S[sp], rate, scheme))
        for mp3, m, spb, rate, scheme in cases:
            subprocess.run([exe, tape, wav, str(m), str(spb), str(rate), str(scheme)],
                           check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            rows.append((mp3, m, spb, rate, scheme, fnv1a64(open(wav, "rb").read())))
    with open(out, "w") as f:
        f.write("// Generated by tools/k7zx43/make_golden.py from tests/data/golden.tap.\n"
                "// FNV-1a 64 hashes of the WAVs the unmodified k7zx 4.3 engine writes.\n"
                "// {low-rate flag, method, samples per bit, rate, requested scheme, hash}\n"
                "// The low-rate mode was removed in step 15, so the flag is always 0.\n")
        for mp3, m, spb, rate, scheme, h in rows:
            f.write(f"{{{mp3}, {m}, {spb}, {rate}, {scheme}, 0x{h:016x}ULL}},\n")
    print(f"{out}: {len(rows)} cases")


if __name__ == "__main__":
    main()
